dist: trusty
language: java
# use Java 8
jdk:
- oraclejdk8

before_install:
- chmod +x gradlew

# see https://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure
sudo: true

before_deploy:
- gradlew jar

deploy:
  provider: releases
  api_key: $yuh
  file: "build/libs/tutor-test-1.0-SNAPSHOT.jar"
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
# cache the build tool's caches
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle

