package com.colinparrott.parallelsimulator.engine.simulator.programs.generators.askoutcome;

public enum GenMethod
{
    RANDOM_MAX_GLOBAL_STEPS, RANDOM_MAX_GLOBAL_STEPS_IGNORE_COMPLETE_THREADS,
    PROBABILISTIC_MOST_STORES_DYNAMIC, PROBABILISTIC_MOST_STORES_STATIC,
    PROBABILISTIC_MOST_STORES_STATIC_SHUFFLE, PROBABILISTIC_MOST_STORES_AND_BRANCHES_STATIC
}
